"""Add Leaderboard table

Revision ID: 8234bc87b75c
Revises: 957b110e6910
Create Date: 2025-06-29 13:43:19.372954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8234bc87b75c'
down_revision: Union[str, Sequence[str], None] = '957b110e6910'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leaderboard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('profit', sa.Float(), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_leaderboard_created_at'), 'leaderboard', ['created_at'], unique=False)
    op.create_index(op.f('ix_leaderboard_id'), 'leaderboard', ['id'], unique=False)
    op.create_index(op.f('ix_leaderboard_uuid'), 'leaderboard', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leaderboard_uuid'), table_name='leaderboard')
    op.drop_index(op.f('ix_leaderboard_id'), table_name='leaderboard')
    op.drop_index(op.f('ix_leaderboard_created_at'), table_name='leaderboard')
    op.drop_table('leaderboard')
    # ### end Alembic commands ###
